/**
 * Auto-generates sitemap.xml from the route list and blog posts.
 * Run after generate-blog-data.ts so BLOG_POSTS is available.
 *
 * Usage: tsx script/generate-sitemap.ts
 */
import { writeFile } from "fs/promises";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "..");
const OUTPUT = path.resolve(ROOT, "client/public/sitemap.xml");
const BASE_URL = "https://buzztate.com";

// Static landing pages with their priorities and change frequencies
const STATIC_ROUTES: { path: string; priority: string; changefreq: string }[] = [
  { path: "/", priority: "1.0", changefreq: "daily" },
  { path: "/amazon-listing-translation", priority: "0.8", changefreq: "weekly" },
  { path: "/shopify-product-translation", priority: "0.8", changefreq: "weekly" },
  { path: "/etsy-listing-translation", priority: "0.8", changefreq: "weekly" },
  { path: "/amazon-de-translation", priority: "0.7", changefreq: "weekly" },
  { path: "/amazon-jp-translation", priority: "0.7", changefreq: "weekly" },
  { path: "/blog", priority: "0.7", changefreq: "weekly" },
];

async function generateSitemap() {
  // Dynamic import of blog data (generated by generate-blog-data.ts)
  const blogDataPath = path.resolve(ROOT, "client/src/pages/blog/blogData.ts");
  // Read the file and extract post metadata
  const { readFile: rf } = await import("fs/promises");
  const blogDataContent = await rf(blogDataPath, "utf-8");

  // Extract blog post slugs and dates from the generated file
  const slugRegex = /"slug":\s*"([^"]+)"/g;
  const dateRegex = /"date":\s*"([^"]+)"/g;
  const updatedRegex = /"updated":\s*"([^"]+)"/g;

  const slugs: string[] = [];
  const dates: string[] = [];
  const updatedDates: string[] = [];

  let match;
  while ((match = slugRegex.exec(blogDataContent)) !== null) slugs.push(match[1]);
  while ((match = dateRegex.exec(blogDataContent)) !== null) dates.push(match[1]);
  while ((match = updatedRegex.exec(blogDataContent)) !== null) updatedDates.push(match[1]);

  const today = new Date().toISOString().split("T")[0];

  let xml = '<?xml version="1.0" encoding="UTF-8"?>\n';
  xml += '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n';

  // Static routes
  for (const route of STATIC_ROUTES) {
    const loc = route.path === "/" ? BASE_URL + "/" : BASE_URL + route.path;
    xml += `   <url>\n`;
    xml += `      <loc>${loc}</loc>\n`;
    xml += `      <lastmod>${today}</lastmod>\n`;
    xml += `      <changefreq>${route.changefreq}</changefreq>\n`;
    xml += `      <priority>${route.priority}</priority>\n`;
    xml += `   </url>\n`;
  }

  // Blog post routes
  for (let i = 0; i < slugs.length; i++) {
    const slug = slugs[i];
    const lastmod = updatedDates[i] || dates[i] || today;
    xml += `   <url>\n`;
    xml += `      <loc>${BASE_URL}/blog/${slug}</loc>\n`;
    xml += `      <lastmod>${lastmod}</lastmod>\n`;
    xml += `      <changefreq>monthly</changefreq>\n`;
    xml += `      <priority>0.6</priority>\n`;
    xml += `   </url>\n`;
  }

  xml += '</urlset>\n';

  await writeFile(OUTPUT, xml);
  console.log(`sitemap: generated ${STATIC_ROUTES.length + slugs.length} URLs → ${OUTPUT}`);
}

generateSitemap().catch((err) => {
  console.error("generate-sitemap failed:", err);
  process.exit(1);
});
