/**
 * Reads all markdown files from /content/blog/, parses frontmatter,
 * converts markdown to HTML, and writes a static TypeScript module
 * that can be imported by the client and prerender pipeline.
 *
 * Run: `tsx script/generate-blog-data.ts`
 */
import { readdir, readFile, writeFile } from "fs/promises";
import path from "path";
import { fileURLToPath } from "url";
import { marked } from "marked";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "..");
const BLOG_DIR = path.resolve(ROOT, "content/blog");
const OUTPUT = path.resolve(ROOT, "client/src/pages/blog/blogData.ts");

interface BlogFAQ {
  question: string;
  answer: string;
}

interface PostMeta {
  slug: string;
  title: string;
  date: string;
  updated?: string;
  excerpt: string;
}

/**
 * Extract FAQ Q&A pairs from markdown body.
 * Looks for a "## FAQ" section, then parses ### headings as questions
 * and the following paragraphs as answers.
 */
function extractFAQs(body: string): BlogFAQ[] {
  const faqStart = body.indexOf("## FAQ");
  if (faqStart === -1) return [];

  const faqSection = body.slice(faqStart);
  // Split by ### headings
  const parts = faqSection.split(/^### /m).slice(1); // skip the "## FAQ" header itself

  return parts.map((part) => {
    const lines = part.trim().split("\n");
    const question = lines[0].trim();
    const answer = lines
      .slice(1)
      .join("\n")
      .trim()
      // Stop at the next ## heading if any
      .split(/^## /m)[0]
      .trim();
    return { question, answer };
  });
}

function parseFrontmatter(raw: string): { meta: Record<string, string>; body: string } {
  const match = raw.match(/^---\n([\s\S]*?)\n---\n([\s\S]*)$/);
  if (!match) return { meta: {}, body: raw };

  const meta: Record<string, string> = {};
  for (const line of match[1].split("\n")) {
    const idx = line.indexOf(":");
    if (idx === -1) continue;
    const key = line.slice(0, idx).trim();
    let val = line.slice(idx + 1).trim();
    if ((val.startsWith('"') && val.endsWith('"')) || (val.startsWith("'") && val.endsWith("'"))) {
      val = val.slice(1, -1);
    }
    meta[key] = val;
  }

  return { meta, body: match[2] };
}

async function generateBlogData() {
  const files = (await readdir(BLOG_DIR)).filter((f) => f.endsWith(".md"));

  const posts: { meta: PostMeta; html: string; faqs: BlogFAQ[] }[] = [];

  for (const file of files) {
    const raw = await readFile(path.resolve(BLOG_DIR, file), "utf-8");
    const { meta, body } = parseFrontmatter(raw);

    const slug = meta.slug || file.replace(/\.md$/, "");
    const html = await marked(body, { async: false });
    const faqs = extractFAQs(body);

    posts.push({
      meta: {
        slug,
        title: meta.title || slug,
        date: meta.date || "2026-01-01",
        updated: meta.updated,
        excerpt: meta.excerpt || "",
      },
      html: html as string,
      faqs,
    });
  }

  // Sort by date descending
  posts.sort((a, b) => b.meta.date.localeCompare(a.meta.date));

  // Generate TypeScript module
  const tsContent = `// AUTO-GENERATED by script/generate-blog-data.ts — do not edit manually
import type { BlogPost } from "@/lib/blog";

export const BLOG_POSTS: BlogPost[] = ${JSON.stringify(
    posts.map((p) => ({ ...p.meta, html: p.html, faqs: p.faqs.length > 0 ? p.faqs : undefined })),
    null,
    2,
  )};
`;

  await writeFile(OUTPUT, tsContent);
  console.log(`blog-data: generated ${posts.length} posts → ${OUTPUT}`);
}

generateBlogData().catch((err) => {
  console.error("generate-blog-data failed:", err);
  process.exit(1);
});
